### ISSUE TITLE
Instalación en el README

### ISSUE THREAD

**Issue by MarianoRD** [adeluccar/epale-bot#1]
Si bien no hay que "instalar" nada para usar el bot, sería bueno que todos los que colaboren en el proyecto tengan NodeJS en su computadora para poder probar que los cambios que hagan funcionen antes de subir los cambios

**Comment by adeluccar** [comment]
En efecto, no he incluido ningún modulo de node por los momentos (aunque tengo varias ideas), esperando que haya mas quorum para tomar decisiones respecto a versión de JS a usar, etc. Así armamos algo a la medida del grupo.

**Comment by adeluccar** [comment]
Instrucciones para instalar node están en [docs/setup.md](https://github.com/adeluccar/epale-bot/blob/master/docs/setup.md)
