### ISSUE TITLE
Setup.md del proyecto

### ISSUE THREAD

**Issue by criptodev** [adeluccar/epale-bot#20]
¿Deberíamos crear un segundo documento?, en este colocariamos todo el tema de instalación de node-js, las guías de estilo, listado de las tecnologías a usar, recomendaciones de editores de texto, y otra cosa que se nos ocurra.

**Comment by german1608** [comment]
Me parece bien. Modifica tu PR #14 para que en vez de editar el `como-contribuir.md` crees el `setup.md` a fin de agregar todo lo que dice.

**Comment by adeluccar** [comment]
@criptodev Buena idea la de @german1608

**Comment by adeluccar** [comment]
Voy a usar este issue para hacer un video explicativo de como trabajar en el proyecto (usando el Como Contribuir) como punto de partida.
