### ISSUE TITLE
Flujo de trabajo

### ISSUE THREAD

**Issue by IsaacYAGI** [adeluccar/epale-bot#21]
Buenas amigos, no se si ya lo definieron explicitamente pero me gustaría saber si ya tienen definido una forma de trabajo.

Es decir, los pullrequest se unirán directo a master siempre, si se utilizará dos ramas: master y develop, tags, releases, etc.

**Comment by adeluccar** [comment]
El workflow que tengo en el documento de Como Contribuir es una abstracción de Github Flow. Las contribuciones de cada rama van directo a mi `master` para luego propagarse a todos los forks. No hay necesidad (por los momentos) de añadir complejidad adicional con ramas `develop`, `hotfix`, etc.

**Comment by IsaacYAGI** [comment]
Ah perfecto entonces, por los momentos se mantendrá con una rama y pull requests, entendido :) Cierro el issue entonces.

¡Saludos!
