### ISSUE TITLE
Que dependencia usaremos

### ISSUE THREAD

**Issue by german1608** [adeluccar/epale-bot#23]
Estuve investigando que es lo necesario para crear bots en telegram usando node.js.
Les tengo dos opciones:

1) [node-telegram-bot-api](https://github.com/yagop/node-telegram-bot-api) Esta me agrada pues esta bien documentada y su ultimo commit es del 15-08-2017. Esta esta orientada a un estilo de programacion mas programatico, secuencial.

2) [telegram-node-bot](https://github.com/Naltox/telegram-node-bot) Esta es otra opcion. Su ultimo commit es del año pasado y esta orientada a MVC usando routers y controllers (mas info en su README.md).

Que opcion les agrada mas?
:+1: por 1)
👎 por 2)

**Comment by adeluccar** [comment]
https://github.com/mullwar/telebot

Commits hace 5 días. Buena documentación.

**Comment by criptodev** [comment]
@german1608 Cual es tu opinion sobre el api que compartio @adeluccar ?.

**Comment by german1608** [comment]
Me parece mas sencillo de usar que los dos que mande. Ademas, el que mando el esta mas estable

**Comment by adeluccar** [comment]
Creo que nos iremos por ese entonces. No veo mas votos desde hace 10 días así creo que es valido considerar usar el de mulwar. Voy a cerrar este issue.
