### ISSUE TITLE
Sintaxis ES6 para el bot

### ISSUE THREAD

**Issue by adeluccar** [adeluccar/epale-bot#3]
¿Alguna objeción a usar ES6?

**Comment by criptodev** [comment]
De acuerdo con usar ES6

_Sent from my Motorola XT1064 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by abrahamjsb** [comment]
No hay problema solo que no se puede utilizar al 100% en node.js

**Comment by adeluccar** [comment]
@abrahamjsb Asumiendo que usamos una versión de Node de largo soporte (6.11.2 en este momento), tenemos acceso a 99% de ES6/ES2015.

http://node.green/
