### ISSUE TITLE
Creacion package.json

### ISSUE THREAD

**Issue by criptodev** [adeluccar/epale-bot#32]
Quien se anima a crear el placeholder?, lo iremos modificando a medida que vayamos requiriendo hacerlo.

**Comment by german1608** [comment]
Que cosas nos gustaria preguntarle al nuevo integrante? coloco aca algunas ideas

1) tabs vs spaces
2) sublime
3) como llego a fcc
4) aspiraciones
5) experiencias
...
Llenen la lista

**Comment by criptodev** [comment]
@german1608 Por que no creas un issue para eso?. Arriba a la derecha hay un boton que dice: New issue

**Comment by german1608** [comment]
ya va, me confundi a lo que te refieres con placeholder...

**Comment by adeluccar** [comment]
Puedo hacerlo mañana. Voy a trabajar con npm para evitar dependencias adicionales (como yarn o pnpm) para quienes no lo tienen instalado. ¿Estaría bien eso?

**Comment by criptodev** [comment]
Si!, mejor trabajar con npm por ahora, mas adelante podemos probar yarn en algun otro proyecto!.

**Comment by adeluccar** [comment]
@criptodev Para poder comenzar a armar esta belleza, hay que solventar lo de la versión de Node a usar (Issue #34 )
