### ISSUE TITLE
Sobre la version de npm

### ISSUE THREAD

**Issue by german1608** [adeluccar/epale-bot#34]
Puede que la mayoria de los aqui presentes tenga versiones distintas de npm.

Deberiamos fijar alguna version en especifico? Lo digo por que `npm v5.x` incluye el archivo 
`package-lock.json` que no incluye `npm v3.x`.

**Comment by adeluccar** [comment]
@german1608 Tiendo a utilizar siempre que sea posible las versiones con soporte a largo plazo (LTS). Por ejemplo, en mi sistema, node es 6.11.0 y el npm que trae dicho node es 3.10.10.

Podemos asegurarnos de que se usen estas versiones usando para ello el campo de engine en el package.json.

¿Que preferirían ustedes? ¿Lo mas nuevo o lo mas estable?

cc @IsaacYAGI @bettoarcaya @criptodev @cristche

**Comment by IsaacYAGI** [comment]
Creo que siempre es mejor utilizar las versiones más estables para evitar la masacre que pasó en Bootstrap 4 donde cambiaron todo jaja.

Yo voto por LTS.

**Comment by german1608** [comment]
Lol no sabia que el `npm 5.x` no era estable. Bueno, es mejor usar siempre lo mas estable. Voto por el 3.x . Vere como hago para cambiar el npm.

**Comment by criptodev** [comment]
Yo no tengo problema, usaré la versión mas nueva, pero si mas de una persona usa la lts, entonces usemos esa. Creo que la versión mas nueva tiene retrocompatibilidad así que es indiferente para mi.

**Comment by adeluccar** [comment]
@german1608 ¿npm no viene con node pues? ;)

**Comment by adeluccar** [comment]
En realidad esta pregunta tiene que ver directamente con node. No con npm.
npm viene con node.js. La decisión en realidad es, ¿que versión de node vamos a usar?

**Comment by german1608** [comment]
@adeluccar Es que yo tengo node LTS y actualize el npm por que pense que ya era estable.

**Comment by adeluccar** [comment]
@criptodev Eso no funciona así, mon friend. Porque estarías trabajando en un entorno distinto al de los demás. Estarías haciendo uso (quizás sin saberlo) features que no están en el LTS. De hecho, el package.json posiblemente te obligue a cambiar la versión.

La clave de entender porque estamos conversando esto es precisamente para evitar el 'funciona en mi maquina' y no en la de los demás.

**Comment by adeluccar** [comment]
@german1608 Si va. Lo mejor es volarte node (si no tienes mucho paquete global instalado) y reinstalar el LTS. Se hace drásticamente mas fácil usando un gestor de ambientes node como nodenv (ver instrucciones docs/setup.md sección Mac).

**Comment by german1608** [comment]
@adeluccar si no encuentro una forma de downgradear el npm, pues tengo mas o menitos paquetes globales

**Comment by german1608** [comment]
Reinstalo node **, pues...

**Comment by adeluccar** [comment]
¿En todo caso estamos de acuerdo en usar LTS (6.11.2 actualmente)?

Votar arriba -> https://github.com/adeluccar/epale-bot/issues/34#issuecomment-327005701

**Comment by IsaacYAGI** [comment]
Ayer fue liberada otra version LTS, asumo que seguiremos usando la version Node_6.11.2 + npm_3.10.10  ¿correcto?

**Comment by german1608** [comment]
@IsaacYAGI Si hermano. Que estemos debajo por un patch no creo que nos afecte mucho.

**Comment by adeluccar** [comment]
Como quieran. Si quieren subir la versión, podemos hacerlo sin mucho rollo. Eso lo podemos hacer en el package.json y en el node-version. Simplemente tienen que asegurarse de instalar la nueva versión y ya.

**Comment by adeluccar** [comment]
@IsaacYAGI @german1608
