### ISSUE TITLE
Guía de Estilo StandardJS

### ISSUE THREAD

**Issue by adeluccar** [adeluccar/epale-bot#4]
StandardJS es una guía de estilo para escribir Javascript. Lo único un poco controversial es que no usa punto y comas para terminar los statements de JS.  Pero la guía en si ayuda a mantener un estilo coordinado entre todos.

Pueden obtener mas información al respecto en https://standardjs.com/

--

Ojo, si estamos de acuerdo, puedo colocar los módulos y el archivo `.eslintrc` para usar esto sin mucho inconveniente.

**Comment by adeluccar** [comment]
La razón mas importante por la que propongo que utilicemos algo como esto, es que así todos escribimos el JS con el mismo estilo. Sino vamos a tener una melcocha. Unos con tabs. Otros con espacios. ¿4 espacios? ¿2? Esto precisamente nos quita la necesidad de discutir esas cosas.

**Comment by criptodev** [comment]
Por ahora usemoslo, ya que no hay nadie en contra ni mejor propuesta, al menos yo considero que es un gran plus practicar usando el mismo estilo, a los que participe los ayudara a mejorar muchisimo el trabajo en equipo.

**Comment by adeluccar** [comment]
Excelente. No veo mayores objeciones. Mañana integro esto en el repositorio.

**Comment by adeluccar** [comment]
Hmm. Olvidé hacer esto @criptodev - mañana lo incluyo en los cambios que comenté en los nuevos issues

**Comment by criptodev** [comment]
Si!, esta es una de las documentaciones pendientes, deberiamos usar este issue o crear otro que invite a quien quiera a crear la documentacion de standardJS.

**Comment by german1608** [comment]
no creo que haga falta crear una documentacion para standardJS. Creo que podriamos colocar un link en algun archivo existente (en el README por ejemplo) que nos mande a standardjs.com y ya

**Comment by criptodev** [comment]
@german1608 El punto de crear la documentacion no es tanto porque sea necesario, es mas para hacerla nosotros mismos, igual que el bot, ya existe un welcome bot y sin embargo lo estamos haciendo para practicar, ademas tambien la documentacion estara en español.

**Comment by german1608** [comment]
mmm tienes razon @criptodev

**Comment by adeluccar** [comment]
@criptodev @german1608 Honestamente no es necesario documentar la guía de estilo StandardJS. Literalmente ese es su propósito.

Lo que podemos hacer es enlazar a la guía en sí.

https://standardjs.com/readme-esla.html

**Comment by adeluccar** [comment]
El modulo que vamos a instalar es simplemente para hacer el enforcement de la guía. Pero la 'documentación' de la guía, es la guía en sí.

Lo que **si** podemos documentar es como instalar (si es necesario) los eslinters en los editores de texto que están usando los que contribuyen al proyecto.
