### ISSUE TITLE
Encontre un detalle en la instalacion en linux (Mi caso, ubuntu)

### ISSUE THREAD

**Issue by german1608** [adeluccar/epale-bot#41]
En el apartado **Linux** de [docs/setup.md](https://github.com/adeluccar/epale-bot/blob/master/docs/setup.md#linux) Encontre dos detalles:

1) El paso 2 dice que luego de descomprimir se encontrara una carpeta `node-v0.10.13` que pues referencia a una version vieja de node.
2) Igualmente entre en en la carpeta que se obtiene al descargar la version LTS por la pagina de nodejs y al descomprimirla no hay un archivo `configure` ni nada por el estilo.

[Aqui](https://asciinema.org/a/IBYsKsTYVK6QOBzukehA6pHTr) un asciinema (video) sobre eso.

**Comment by adeluccar** [comment]
Ok. Documenta los procesos que estas llevando. Nada cambia mas la documentación que alguien que esta dandonse golpes con la misma.

¿A manera de curiosidad, nodenv no funciona en linux también?

**Comment by german1608** [comment]
No estoy seguro si funciona en linux. Crees que deberia montar un PR con el metodo de instalacion que yo uso? Crees que al hacer este deberia eliminar el metodo de instalacion que esta ya propuesto?

**Comment by adeluccar** [comment]
Si el método actual no funciona consistentemente, es buena idea iterar hasta conseguir un método que funcione.

**Comment by adeluccar** [comment]
Arreglado con PR #43
