### ISSUE TITLE
Manual de Uso Git

### ISSUE THREAD

**Issue by adeluccar** [adeluccar/epale-bot#5]
Necesitamos armar un manual de proyecto sobre como usar Git, paso a paso.
¿Quizás un document adicional en Markdown vs. la Wiki? Así podemos usarlo para seguir practicando Git.

**Comment by bettoarcaya** [comment]
hola a todos, el manual parte desde la instalación de git?

**Comment by adeluccar** [comment]
Creo que un link a buenos recursos sobre cómo instalar Git para cada sistema operativo estaría bien.

**Comment by bettoarcaya** [comment]
chicos que tal? eh estado trabajando un poquito en el manual. que dicen lo agregamos a la wiki o en markdown? en mi opinión prefiero en la wiki.

**Comment by adeluccar** [comment]
Mejor en markdown. Para que este dentro del repo. Puedes incluir un dir /docs y armar ahí un .md - sabes cómo armar la rama, pull request, etc?

**Comment by bettoarcaya** [comment]
oks, déjame investigar un poco de como incluir un dir/docs. si fuese una wiki no estaría dentro del repo?

**Comment by adeluccar** [comment]
No hasta donde tengo entendido. Dejame revisar a ver.

**Comment by adeluccar** [comment]
Oh! Ya entendí la cosa. La wiki es *otro* repositorio git asociado a la cuenta. Puede ser que valga la pena entonces. Creo que no tengo ningún problema en usar la wiki para estos propósitos (y así mantenemos el tamaño de la repo general contenido).

**Comment by adeluccar** [comment]
No se muy bien como hacen las referencias de los issues y los commits las wikis, pero acabo de montar un documento sobre como contribuir al documento (reciclado de un documento similar que redacté para otro proyecto). Voy a cerrar este issue, pues ya el problema al que se refiere esta resuelto.

https://github.com/adeluccar/epale-bot/wiki/Como-Contribuir
