### ISSUE TITLE
¿Quién va a ser el Gerente del Proyecto?

### ISSUE THREAD

**Issue by adeluccar** [adeluccar/epale-bot#6]
Muchachos, ¿quién tiene la experiencia para gerenciar el proyecto?

Yo puedo fungir como integrador de los commits (no en vano la repo esta en mi cuenta), pero sería bueno considerar la posibilidad de que haya una persona que tome la decisión final respecto a algún issue o feature. Puede ser también un comité de 3 personas. 

¿O prefieren dejarlo a voto popular en los comentarios de los Issues?
¿Qué opinan?

**Comment by criptodev** [comment]
Yo prefiero voto popular, probablemente quien tenga exp para esto, tendrá poco tiempo y puede frenarnos ocasionalmente. 

_Sent from my Motorola XT1064 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by abrahamjsb** [comment]
No se puede crear una organización de Github de FCC Caracas? Se pueden tener los proyectos en esa organización. Por cierto Saludos a todos jeje ando perdido.

**Comment by adeluccar** [comment]
@abrahamjsb Tengo mis dudas al respecto (pues quizás pueda haber problemas con el branding). Si me preguntas a mi, yo buscaría armar una organización nuestra.

**Comment by criptodev** [comment]
Si, es buena idea lo de la organización, voy a preguntar a algún pro de fcc a ver que me dicen.

**Comment by criptodev** [comment]
Aunque la organización no resuelve el problema de quien gerencia.

**Comment by abrahamjsb** [comment]
En el foro de FCC se puede preguntar. Si algo resuelve es que los proyectos del grupo queden en un grupo y no como tal en repos personales de las personas. Por otro lado @criptodev tu eres fundador de la comunidad, eres el administrador  lo que te queda es  definir quienes te van apoyar que sean recurrentes en la comunidad eso es todo bro.

**Comment by criptodev** [comment]
@abrahamjsb Bueno, ya @adeluccar se ofrecio como integrador de commits, puedo designar a alguien para gerenciar, siempre y cuando acepte tomar la responsabilidad y tenga el tiempo de contribuir, tu quisieras tener algun rol especifico?, y mas importante tienes tiempo de.

**Comment by abrahamjsb** [comment]
Hola @criptodev sorry por  la tardanza. Te mentiria si te dijera que no me gustaría entrar, siempre me gusta colaborar pero en estos momentos no creo que ser la persona adecuada porque no tengo la disponibilidad para hacerlo. Sin embargo, cuando tenga chance siempre echaré una mano en el código si cabe dentro de mis capacidades. Saludos bro!

**Comment by adeluccar** [comment]
Creo que no hay necesidad (ni mucho interés por parte de ninguno - jajaja). Usemos el voto para manejar los issues y los issues para llevar el roadmap. Si vemos que se complica la cosa, podemos reactivar este issue.
