### ISSUE TITLE
Ajustes en la documentación de Como Contribuir

### ISSUE THREAD

**Issue by IsaacYAGI** [adeluccar/epale-bot#7]
Buenas amigos, soy nuevo en esto así que no estoy seguro si este es el lugar indicado para mencionarlo.

Revisando la [Wiki](https://github.com/adeluccar/epale-bot/wiki/Como-Contribuir) me di cuenta que el comando de clone hace referencia al modo utilizando el key SSH. 

No sé si sería mejor cambiar las instrucciones para utilizar el modo HTTPS ya que es más directo (y no requiere generar una llave), o poner ambos modos. O en tal caso linkear a una documentación donde expliquen como hacer esto.

Me imagino que lo mismo aplicaría para la configuración del upstream.

Y creo que fue un error de tipeo también donde dice "En tu sistema local, haz un ```git clone git@github.com:adeluccar/epale-bot.git``` donde **usuario** es tu usuario en github." puesto que la palabra "usuario" no está presente en el comando jeje, quizás esto puede generar alguna que otra confusión.

PD: No sé si el issue quedó muy grande y debí dividirlo en dos o tres, ¡mis disculpas de antemano por esto!

Saludos.

**Comment by adeluccar** [comment]
Gracias por avisar @IsaacYAGI 

En efecto, hay un par de cosas que hay que ajustar. Buena idea lo del https vs. ssh para quienes lo usan de esa forma.

Igual voy a retirar la wiki porque es dificil para los demas contribuir a esta sin tener que añadir manualmente a colaboradores. El documento va a estar en un directorio docs/ del repositorio general.

**Comment by criptodev** [comment]
A mi tambien me gusta mas el modo HTTPS

**Comment by adeluccar** [comment]
@IsaacYAGI Lo del adeluccar ya lo arreglé en ese punto. Respecto a https, ¿alguien quiere hacer la prueba de agregarlo?

**Comment by IsaacYAGI** [comment]
Listo @adeluccar , acabo de hacer el pullrequest #17 , si puedes echarle un vistazo estaria agradecido :)

**Comment by adeluccar** [comment]
Cierro issue pues PR #17 lo soluciona. Gracias @IsaacYAGI
